import { writeTextAtomically as writeFileSync } from "./write.mjs";
/**
 * Course generator (CNT-10): expands the hand-authored course with themed,
 * grammar-focused units built from the lexicon in generator/lexicon.mjs.
 *
 *   node generator/generate.mjs            # full run
 *   node generator/generate.mjs --scale .02  # small sample, for eyeballing
 *   node generator/generate.mjs --clean      # remove generated units and stop
 *
 * Default runs append missing units without changing published lessons.
 * Use --rebuild only for an intentional full content replacement.
 *
 * Generated units are written as ordinary YAML into course/en-tl/units, named
 * so they sort *inside* their tier's run (tier contiguity is enforced by the
 * compiler). Default runs retain published units. --rebuild explicitly replaces
 * generated units; hand-authored units are never rewritten.
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse, stringify } from "yaml";

import { rngFrom, slug } from "./grammar.mjs";
import { buildUnit } from "./build.mjs";
import { themeSupports } from "./context.mjs";
import { THEMES } from "./themes.mjs";
import { FOUNDATION_FOCUSES } from "./focus-foundation.mjs";
import { EVERYDAY_FOCUSES } from "./focus-everyday.mjs";
import { CONVERSATIONAL_FOCUSES } from "./focus-conversational.mjs";
import { MASTERY_FOCUSES, IDIOMS } from "./focus-mastery.mjs";
import { ADJECTIVES, COLORS, NOUNS, NUMBERS, STATES, TIMES, VERBS } from "./lexicon.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const courseDir = join(root, "course", "en-tl");
const unitsDir = join(courseDir, "units");

/** how many units each tier gets, and where their files sort */
const TIERS = [
  { id: "foundation", focuses: FOUNDATION_FOCUSES, units: 864, prefix: "18t-g", xp: 10 },
  { id: "everyday", focuses: EVERYDAY_FOCUSES, units: 816, prefix: "35r-g", xp: 15 },
  { id: "conversational", focuses: CONVERSATIONAL_FOCUSES, units: 768, prefix: "51q-g", xp: 20 },
  { id: "mastery", focuses: MASTERY_FOCUSES, units: 288, prefix: "57g-g", xp: 25 },
];

const GENERATED_MARK = "# generated by generator/generate.mjs — edit the generator, not this file";

function args() {
  const argv = process.argv.slice(2);
  const scale = Number((argv.find((a) => a.startsWith("--scale")) ?? "").split("=")[1] ?? argv[argv.indexOf("--scale") + 1] ?? 1);
  return {
    scale: Number.isFinite(scale) && scale > 0 ? scale : 1,
    clean: argv.includes("--clean"),
    bump: argv.includes("--bump"),
    rebuild: argv.includes("--rebuild"),
  };
}

function removeGenerated() {
  let removed = 0;
  for (const file of readdirSync(unitsDir)) {
    if (!file.endsWith(".yaml")) continue;
    if (!TIERS.some((t) => file.startsWith(t.prefix))) continue;
    rmSync(join(unitsDir, file));
    removed += 1;
  }
  return removed;
}

/** every unit id already in use, so generated ids can never shadow one */
function existingUnitIds() {
  const ids = new Set();
  for (const file of readdirSync(unitsDir)) {
    if (!file.endsWith(".yaml")) continue;
    const doc = parse(readFileSync(join(unitsDir, file), "utf8"));
    if (doc && doc.id) ids.add(doc.id);
  }
  return ids;
}

function main() {
  const { scale, clean, bump, rebuild } = args();
  if (!existsSync(unitsDir)) mkdirSync(unitsDir, { recursive: true });

  const removed = clean || rebuild ? removeGenerated() : 0;
  if (clean) {
    console.log(`removed ${removed} generated unit files`);
    return;
  }

  const usedIds = existingUnitIds();
  const idFor = (base) => {
    let id = slug(base).replace(/_/g, "-");
    let n = 2;
    while (usedIds.has(id)) id = `${slug(base).replace(/_/g, "-")}-${n++}`;
    usedIds.add(id);
    return id;
  };

  // one course-wide set: no generated unit repeats another's sentence
  const seen = new Set();
  const published = readdirSync(unitsDir).filter((file) => file.endsWith(".yaml"))
    .map((file) => ({ file, unit: parse(readFileSync(join(unitsDir, file), "utf8")) }));
  // Existing lessons are a published contract: keep IDs, answers, and order.
  // Seed deduplication with their actual sentence content before adding units.
  const remember = (value) => {
    if (typeof value !== "string") return;
    seen.add(value.normalize("NFD").replace(/[\u0300-\u036f]/g, "")
      .toLowerCase().replace(/[.,!?¡¿;:'"“”‘’()]/g, "").replace(/\s+/g, " ").trim());
  };
  for (const { unit } of published) for (const lesson of unit.lessons ?? []) {
    for (const exercise of lesson.exercises) {
      remember(exercise.prompt_tl);
      remember(exercise.answer_tl);
    }
  }
  const stats = { units: 0, lessons: 0, exercises: 0, skipped: 0 };
  const usedWords = new Set();

  for (const tier of TIERS) {
    const quota = Math.max(1, Math.round(tier.units * scale));
    const rng = rngFrom(`plan:${tier.id}`);
    // walk the theme x focus grid in a fixed shuffled order, then go round
    // again with a higher pass number when a tier needs more units than the
    // grid holds (pass 2 draws different sentences from the same pool)
    const grid = [];
    for (const focus of tier.focuses) {
      for (const theme of THEMES) {
        if (!focus.makers.some((m) => themeSupports(theme, m.needs))) continue;
        grid.push({ focus, theme });
      }
    }
    const order = rng.shuffle(grid);

    const existing = published.filter(({ file }) => file.startsWith(tier.prefix));
    let made = existing.length;
    // New deterministic passes don't disturb previously published lessons.
    let pass = existing.length ? 2 : 1;
    let fileIndex = existing.reduce((max, { file }) => Math.max(max,
      Number(file.slice(tier.prefix.length).match(/^\d+/)?.[0] ?? 0)), 0) + 1;
    while (made < quota && pass <= 12) {
      for (const { focus, theme } of order) {
        if (made >= quota) break;
        const unit = buildUnit({
          focus,
          theme,
          index: pass,
          seed: `${tier.id}:${focus.id}:${theme.id}:${pass}`,
          seen,
          xp: tier.xp,
          idFor,
        });
        if (!unit) {
          stats.skipped += 1;
          continue;
        }
        const name = `${tier.prefix}${String(fileIndex).padStart(4, "0")}-${slug(`${theme.id}-${focus.id}`).replace(/_/g, "-")}.yaml`;
        writeFileSync(
          join(unitsDir, name),
          `${GENERATED_MARK}\n${stringify(unit, { lineWidth: 0 })}`,
          "utf8",
        );
        collectWords(unit, usedWords);
        made += 1;
        fileIndex += 1;
        stats.units += 1;
        stats.lessons += unit.lessons.length;
        stats.exercises += unit.lessons.reduce((n, l) => n + l.exercises.length, 0);
      }
      pass += 1;
    }
    console.log(`  ${tier.id}: ${made} units (${grid.length} theme×focus combos, ${pass - 1} passes)`);
    if (made < quota) throw new Error(`${tier.id}: generated ${made} of ${quota} requested units; add reviewed templates before raising the quota`);
  }

  const addedVocab = mergeVocab();
  if (bump && (stats.units > 0 || addedVocab > 0)) bumpVersion();

  console.log(
    `✓ generated ${stats.units} units, ${stats.lessons} lessons, ${stats.exercises} exercises; ` +
      `${addedVocab} new vocab entries (${stats.skipped} combos skipped for thin material)`,
  );
}

function collectWords(unit, into) {
  for (const lesson of unit.lessons)
    for (const ex of lesson.exercises)
      if (ex.type === "match") for (const p of ex.pairs) into.add(p.tl);
}

/**
 * Adds every lexicon word the generator can use to vocab.yaml (skipping lemmas
 * the hand-authored list already carries) so practice mode and the phrasebook
 * see the new material too.
 */
function mergeVocab() {
  const file = join(courseDir, "vocab.yaml");
  const raw = readFileSync(file, "utf8");
  const existing = parse(raw) ?? [];
  const lemmas = new Set(existing.map((v) => String(v.lemma).toLowerCase()));
  const ids = new Set(existing.map((v) => v.id));

  const candidates = [
    ...NOUNS.map((n) => ({ lemma: n.tl, translation: n.en })),
    ...ADJECTIVES.map((a) => ({ lemma: a.tl, translation: a.en })),
    ...STATES.map((s) => ({ lemma: s.tl, translation: s.en })),
    ...COLORS.map((c) => ({ lemma: c.tl, translation: c.en })),
    ...NUMBERS.map((n) => ({ lemma: n.tl, translation: n.en })),
    ...TIMES.map((t) => ({ lemma: t.tl, translation: t.en })),
    ...VERBS.flatMap((v) => [
      { lemma: v.f.inf, translation: `to ${v.en.base}` },
      { lemma: v.f.comp, translation: v.en.past },
      { lemma: v.f.prog, translation: `is ${v.en.ing}` },
    ]),
    ...IDIOMS.map((i) => ({ lemma: i.tl, translation: i.en, notes: `Literally: ${i.lit}.` })),
  ];

  const added = [];
  for (const c of candidates) {
    const key = c.lemma.toLowerCase();
    if (lemmas.has(key)) continue;
    lemmas.add(key);
    let id = slug(c.lemma);
    let n = 2;
    while (ids.has(id)) id = `${slug(c.lemma)}_${n++}`;
    ids.add(id);
    added.push({ id, lemma: c.lemma, translation: c.translation, audio: id, ...(c.notes ? { notes: c.notes } : {}) });
  }
  if (added.length === 0) return 0;

  // Append only: replacing the generated section would delete previously
  // published vocabulary whenever a later run introduced a new lexicon word.
  const base = raw.replace(/\s*$/, "\n");
  writeFileSync(file, `${base}\n# Additional generated vocabulary\n${stringify(added, { lineWidth: 0 })}`, "utf8");
  return added.length;
}

/** published content changed, so the bundle version has to move */
function bumpVersion() {
  const file = join(courseDir, "course.yaml");
  const raw = readFileSync(file, "utf8");
  const current = Number(parse(raw).version);
  const next = current + 1;
  writeFileSync(file, raw.replace(/^version:\s*\d+$/m, `version: ${next}`), "utf8");
  console.log(`  course version ${current} -> ${next}`);
}

main();
