/**
 * The generator's lexicon: every word the templates are allowed to use.
 *
 * Verb forms are authored out in full (completed / progressive / contemplated
 * / infinitive, plus the object-focus set where the verb has a natural one)
 * rather than derived, because -um- infixing, CV reduplication and the -in/-an
 * object forms carry too many exceptions to generate safely.
 *
 * Nouns carry `cat` so verbs can pick sensible objects (you drink a drink and
 * cook food), `mass: true` where English takes no article ("I ate rice"), and
 * `pl` only for irregular English plurals.
 */

const n = (tl, en, theme, cat = "thing", opts = {}) => ({ tl, en, theme, cat, ...opts });

// --------------------------------------------------------------------- nouns

export const NOUNS = [
  // ---- food ----
  n("kanin", "rice", "food", "food", { mass: true }),
  n("tinapay", "bread", "food", "food", { mass: true }),
  n("isda", "fish", "food", "food", { pl: "fish" }),
  n("karne", "meat", "food", "food", { mass: true }),
  n("manok", "chicken", "food", "food", { mass: true }),
  n("baboy", "pork", "food", "food", { mass: true }),
  n("baka", "beef", "food", "food", { mass: true }),
  n("itlog", "egg", "food", "food"),
  n("adobo", "adobo", "food", "food", { mass: true }),
  n("sinigang", "sinigang", "food", "food", { mass: true }),
  n("pansit", "pancit", "food", "food", { mass: true }),
  n("lugaw", "rice porridge", "food", "food", { mass: true }),
  n("sopas", "soup", "food", "food", { mass: true }),
  n("sabaw", "broth", "food", "food", { mass: true }),
  n("gulay", "vegetable", "food", "food"),
  n("prutas", "fruit", "food", "food"),
  n("keso", "cheese", "food", "food", { mass: true }),
  n("asukal", "sugar", "food", "food", { mass: true }),
  n("asin", "salt", "food", "food", { mass: true }),
  n("mantika", "cooking oil", "food", "food", { mass: true }),
  n("sorbetes", "ice cream", "food", "food", { mass: true }),
  n("meryenda", "snack", "food", "food"),

  // ---- breakfast / bakery ----
  n("pandesal", "bread roll", "breakfast", "food"),
  n("sinangag", "fried rice", "breakfast", "food", { mass: true }),
  n("tuyo", "dried fish", "breakfast", "food", { mass: true }),
  n("tapa", "cured beef", "breakfast", "food", { mass: true }),
  n("longganisa", "sausage", "breakfast", "food"),
  n("mantikilya", "butter", "breakfast", "food", { mass: true }),
  n("palaman", "spread", "breakfast", "food", { mass: true }),
  n("champorado", "chocolate rice porridge", "breakfast", "food", { mass: true }),
  n("almusal", "breakfast", "breakfast", "food", { mass: true }),
  n("hapunan", "dinner", "breakfast", "food", { mass: true }),
  n("tanghalian", "lunch", "breakfast", "food", { mass: true }),
  n("panaderya", "bakery", "breakfast", "place"),

  // ---- fruits ----
  n("mansanas", "apple", "fruits", "food"),
  n("saging", "banana", "fruits", "food"),
  n("mangga", "mango", "fruits", "food"),
  n("papaya", "papaya", "fruits", "food"),
  n("pinya", "pineapple", "fruits", "food"),
  n("ubas", "grape", "fruits", "food"),
  n("dalandan", "orange", "fruits", "food"),
  n("bayabas", "guava", "fruits", "food"),
  n("pakwan", "watermelon", "fruits", "food"),
  n("buko", "young coconut", "fruits", "food"),
  n("melon", "melon", "fruits", "food"),
  n("kalamansi", "calamansi", "fruits", "food"),
  n("santol", "santol", "fruits", "food"),
  n("lansones", "lanzones", "fruits", "food", { mass: true }),

  // ---- vegetables ----
  n("kamatis", "tomato", "vegetables", "food", { pl: "tomatoes" }),
  n("sibuyas", "onion", "vegetables", "food"),
  n("bawang", "garlic", "vegetables", "food", { mass: true }),
  n("talong", "eggplant", "vegetables", "food"),
  n("kalabasa", "squash", "vegetables", "food", { pl: "squashes" }),
  n("repolyo", "cabbage", "vegetables", "food"),
  n("karot", "carrot", "vegetables", "food"),
  n("patatas", "potato", "vegetables", "food", { pl: "potatoes" }),
  n("ampalaya", "bitter gourd", "vegetables", "food"),
  n("sitaw", "string bean", "vegetables", "food"),
  n("malunggay", "moringa", "vegetables", "food", { mass: true }),
  n("luya", "ginger", "vegetables", "food", { mass: true }),
  n("mais", "corn", "vegetables", "food", { mass: true }),
  n("kangkong", "water spinach", "vegetables", "food", { mass: true }),

  // ---- drinks ----
  n("tubig", "water", "drinks", "drink", { mass: true }),
  n("kape", "coffee", "drinks", "drink", { mass: true }),
  n("gatas", "milk", "drinks", "drink", { mass: true }),
  n("tsaa", "tea", "drinks", "drink", { mass: true }),
  n("juice", "juice", "drinks", "drink", { mass: true }),
  n("softdrink", "soda", "drinks", "drink", { mass: true }),
  n("serbesa", "beer", "drinks", "drink", { mass: true }),
  n("tsokolate", "hot chocolate", "drinks", "drink", { mass: true }),
  n("yelo", "ice", "drinks", "thing", { mass: true }),
  n("baso", "glass", "drinks", "thing", { pl: "glasses" }),
  n("tasa", "cup", "drinks", "thing"),
  n("bote", "bottle", "drinks", "thing"),

  // ---- market ----
  n("palengke", "market", "market", "place"),
  n("tindahan", "store", "market", "place"),
  n("tindera", "vendor", "market", "person"),
  n("presyo", "price", "market", "abstract"),
  n("timbangan", "scale", "market", "thing"),
  n("supot", "plastic bag", "market", "thing"),
  n("bayong", "woven basket", "market", "thing"),
  n("listahan", "list", "market", "thing"),
  n("kilo", "kilo", "market", "thing"),
  n("sako", "sack", "market", "thing"),
  n("puwesto", "stall", "market", "place"),
  n("suki", "regular customer", "market", "person"),

  // ---- restaurant ----
  n("restawran", "restaurant", "restaurant", "place"),
  n("menu", "menu", "restaurant", "thing"),
  n("waiter", "waiter", "restaurant", "person"),
  n("mesa", "table", "restaurant", "thing"),
  n("upuan", "seat", "restaurant", "thing"),
  n("plato", "plate", "restaurant", "thing"),
  n("kutsara", "spoon", "restaurant", "thing"),
  n("tinidor", "fork", "restaurant", "thing"),
  n("kutsilyo", "knife", "restaurant", "thing", { pl: "knives" }),
  n("tisyu", "tissue", "restaurant", "thing"),
  n("resibo", "receipt", "restaurant", "thing"),
  n("order", "order", "restaurant", "thing"),

  // ---- kitchen ----
  n("kusina", "kitchen", "kitchen", "place"),
  n("kaldero", "pot", "kitchen", "thing"),
  n("kawali", "frying pan", "kitchen", "thing"),
  n("sandok", "ladle", "kitchen", "thing"),
  n("kalan", "stove", "kitchen", "thing"),
  n("repridyereytor", "refrigerator", "kitchen", "thing"),
  n("hurno", "oven", "kitchen", "thing"),
  n("lababo", "sink", "kitchen", "thing"),
  n("mangkok", "bowl", "kitchen", "thing"),
  n("takip", "lid", "kitchen", "thing"),
  n("kahoy", "firewood", "kitchen", "thing", { mass: true }),
  n("resipe", "recipe", "kitchen", "thing"),

  // ---- home ----
  n("bahay", "house", "home", "place", { pl: "houses" }),
  n("kuwarto", "room", "home", "place"),
  n("sala", "living room", "home", "place"),
  n("banyo", "bathroom", "home", "place"),
  n("hagdan", "stairs", "home", "thing", { pl: "stairs" , noObj: true }),
  n("pinto", "door", "home", "thing"),
  n("bintana", "window", "home", "thing"),
  n("bubong", "roof", "home", "thing", { noObj: true }),
  n("dingding", "wall", "home", "thing", { noObj: true }),
  n("sahig", "floor", "home", "thing", { noObj: true }),
  n("hardin", "garden", "home", "place"),
  n("bakuran", "yard", "home", "place"),

  // ---- furniture ----
  n("silya", "chair", "furniture", "thing"),
  n("kama", "bed", "furniture", "thing"),
  n("aparador", "cabinet", "furniture", "thing"),
  n("sopa", "sofa", "furniture", "thing"),
  n("istante", "shelf", "furniture", "thing", { pl: "shelves" }),
  n("unan", "pillow", "furniture", "thing"),
  n("kumot", "blanket", "furniture", "thing"),
  n("ilaw", "light", "furniture", "thing"),
  n("kurtina", "curtain", "furniture", "thing"),
  n("orasan", "clock", "furniture", "thing"),
  n("salamin", "mirror", "furniture", "thing"),
  n("alpombra", "rug", "furniture", "thing"),

  // ---- clothes ----
  n("damit", "shirt", "clothes", "thing"),
  n("pantalon", "pants", "clothes", "thing", { pl: "pants" }),
  n("sapatos", "shoe", "clothes", "thing"),
  n("tsinelas", "slipper", "clothes", "thing"),
  n("medyas", "sock", "clothes", "thing"),
  n("sumbrero", "hat", "clothes", "thing"),
  n("bestida", "dress", "clothes", "thing", { pl: "dresses" }),
  n("palda", "skirt", "clothes", "thing"),
  n("kamiseta", "t-shirt", "clothes", "thing"),
  n("dyaket", "jacket", "clothes", "thing"),
  n("sinturon", "belt", "clothes", "thing"),
  n("relo", "watch", "clothes", "thing", { pl: "watches" }),
  n("kuwintas", "necklace", "clothes", "thing"),
  n("payong", "umbrella", "clothes", "thing"),

  // ---- body ----
  n("ulo", "head", "body", "bodypart"),
  n("mata", "eye", "body", "bodypart"),
  n("ilong", "nose", "body", "bodypart"),
  n("bibig", "mouth", "body", "bodypart"),
  n("tainga", "ear", "body", "bodypart"),
  n("kamay", "hand", "body", "bodypart"),
  n("paa", "foot", "body", "bodypart", { pl: "feet" }),
  n("braso", "arm", "body", "bodypart"),
  n("binti", "leg", "body", "bodypart"),
  n("tiyan", "stomach", "body", "bodypart"),
  n("likod", "back", "body", "bodypart"),
  n("buhok", "hair", "body", "bodypart", { mass: true }),
  n("ngipin", "tooth", "body", "bodypart", { pl: "teeth" }),
  n("puso", "heart", "body", "bodypart"),
  n("mukha", "face", "body", "bodypart"),
  n("leeg", "neck", "body", "bodypart"),

  // ---- health ----
  n("doktor", "doctor", "health", "person"),
  n("ospital", "hospital", "health", "place"),
  n("gamot", "medicine", "health", "thing", { mass: true }),
  n("sakit", "pain", "health", "abstract", { mass: true }),
  n("lagnat", "fever", "health", "abstract", { mass: true }),
  n("ubo", "cough", "health", "abstract"),
  n("sipon", "cold", "health", "abstract", { mass: true }),
  n("sugat", "wound", "health", "abstract"),
  n("nars", "nurse", "health", "person"),
  n("klinika", "clinic", "health", "place"),
  n("bitamina", "vitamin", "health", "thing"),
  n("resepta", "prescription", "health", "thing"),

  // ---- family ----
  n("nanay", "mother", "family", "person", { pl: "mothers" }),
  n("tatay", "father", "family", "person"),
  n("kapatid", "sibling", "family", "person"),
  n("anak", "child", "family", "person", { pl: "children" }),
  n("lolo", "grandfather", "family", "person"),
  n("lola", "grandmother", "family", "person"),
  n("tita", "aunt", "family", "person"),
  n("tito", "uncle", "family", "person"),
  n("pinsan", "cousin", "family", "person"),
  n("asawa", "spouse", "family", "person"),
  n("pamilya", "family", "family", "person", { pl: "families" }),
  n("apo", "grandchild", "family", "person", { pl: "grandchildren" }),

  // ---- people ----
  n("tao", "person", "people", "person", { pl: "people" }),
  n("bata", "child", "people", "person", { pl: "children" }),
  n("lalaki", "man", "people", "person", { pl: "men" }),
  n("babae", "woman", "people", "person", { pl: "women" }),
  n("matanda", "elder", "people", "person"),
  n("kaibigan", "friend", "people", "person"),
  n("kapitbahay", "neighbor", "people", "person"),
  n("bisita", "guest", "people", "person"),
  n("kasama", "companion", "people", "person"),
  n("dayuhan", "foreigner", "people", "person"),
  n("binata", "young man", "people", "person"),
  n("dalaga", "young woman", "people", "person"),

  // ---- jobs ----
  n("guro", "teacher", "jobs", "person"),
  n("pulis", "police officer", "jobs", "person"),
  n("drayber", "driver", "jobs", "person"),
  n("magsasaka", "farmer", "jobs", "person"),
  n("mangingisda", "fisherman", "jobs", "person", { pl: "fishermen" }),
  n("karpintero", "carpenter", "jobs", "person"),
  n("inhinyero", "engineer", "jobs", "person"),
  n("abogado", "lawyer", "jobs", "person"),
  n("kusinero", "cook", "jobs", "person"),
  n("sundalo", "soldier", "jobs", "person"),
  n("artista", "actor", "jobs", "person"),
  n("sekretarya", "secretary", "jobs", "person", { pl: "secretaries" }),
  n("katulong", "helper", "jobs", "person"),
  n("bumbero", "firefighter", "jobs", "person"),

  // ---- school ----
  n("paaralan", "school", "school", "place"),
  n("estudyante", "student", "school", "person"),
  n("libro", "book", "school", "thing"),
  n("papel", "paper", "school", "thing", { mass: true }),
  n("lapis", "pencil", "school", "thing", { pl: "pencils" }),
  n("bolpen", "pen", "school", "thing"),
  n("pisara", "blackboard", "school", "thing"),
  n("silid-aralan", "classroom", "school", "place"),
  n("aralin", "lesson", "school", "abstract"),
  n("pagsusulit", "exam", "school", "abstract"),
  n("bag", "bag", "school", "thing"),
  n("kuwaderno", "notebook", "school", "thing"),
  n("takdang-aralin", "homework", "school", "abstract", { mass: true }),
  n("guhit", "drawing", "school", "thing"),

  // ---- work ----
  n("opisina", "office", "work", "place"),
  n("trabaho", "job", "work", "abstract"),
  n("kompyuter", "computer", "work", "thing"),
  n("papeles", "papers", "work", "thing", { pl: "papers" }),
  n("pulong", "meeting", "work", "abstract"),
  n("amo", "boss", "work", "person", { pl: "bosses" }),
  n("sahod", "salary", "work", "abstract", { pl: "salaries" }),
  n("kliyente", "client", "work", "person"),
  n("ulat", "report", "work", "thing"),
  n("proyekto", "project", "work", "abstract"),
  n("bakasyon", "vacation", "work", "abstract"),
  n("kontrata", "contract", "work", "thing"),

  // ---- technology ----
  n("selpon", "cellphone", "technology", "thing"),
  n("internet", "internet", "technology", "abstract", { mass: true }),
  n("mensahe", "message", "technology", "thing"),
  n("tawag", "call", "technology", "abstract"),
  n("larawan", "photo", "technology", "thing"),
  n("bidyo", "video", "technology", "thing"),
  n("password", "password", "technology", "thing"),
  n("tsarger", "charger", "technology", "thing"),
  n("app", "app", "technology", "thing"),
  n("email", "email", "technology", "thing"),
  n("signal", "signal", "technology", "abstract", { noObj: true }),
  n("baterya", "battery", "technology", "thing", { pl: "batteries" }),

  // ---- transport ----
  n("bus", "bus", "transport", "thing", { pl: "buses" }),
  n("dyip", "jeepney", "transport", "thing"),
  n("traysikel", "tricycle", "transport", "thing"),
  n("kotse", "car", "transport", "thing"),
  n("motorsiklo", "motorcycle", "transport", "thing"),
  n("bangka", "boat", "transport", "thing"),
  n("eroplano", "airplane", "transport", "thing"),
  n("tren", "train", "transport", "thing"),
  n("bisikleta", "bicycle", "transport", "thing"),
  n("taksi", "taxi", "transport", "thing"),
  n("barko", "ship", "transport", "thing"),
  n("gulong", "tire", "transport", "thing"),

  // ---- travel ----
  n("bagahe", "luggage", "travel", "thing", { mass: true }),
  n("tiket", "ticket", "travel", "thing"),
  n("pasaporte", "passport", "travel", "thing"),
  n("hotel", "hotel", "travel", "place"),
  n("paliparan", "airport", "travel", "place"),
  n("biyahe", "trip", "travel", "abstract"),
  n("mapa", "map", "travel", "thing"),
  n("turista", "tourist", "travel", "person"),
  n("terminal", "terminal", "travel", "place"),
  n("isla", "island", "travel", "place"),
  n("probinsya", "province", "travel", "place"),
  n("gabay", "guide", "travel", "person"),

  // ---- town ----
  n("bayan", "town", "town", "place"),
  n("lungsod", "city", "town", "place", { pl: "cities" }),
  n("simbahan", "church", "town", "place", { pl: "churches" }),
  n("plaza", "plaza", "town", "place"),
  n("bangko", "bank", "town", "place"),
  n("mall", "mall", "town", "place"),
  n("parke", "park", "town", "place"),
  n("munisipyo", "town hall", "town", "place"),
  n("sinehan", "cinema", "town", "place"),
  n("kalye", "street", "town", "place"),
  n("kanto", "corner", "town", "place"),
  n("tulay", "bridge", "town", "place"),

  // ---- nature ----
  n("bundok", "mountain", "nature", "place"),
  n("dagat", "sea", "nature", "place"),
  n("ilog", "river", "nature", "place"),
  n("puno", "tree", "nature", "thing"),
  n("bulaklak", "flower", "nature", "thing"),
  n("ulap", "cloud", "nature", "thing", { noObj: true }),
  n("araw", "sun", "nature", "thing", { noObj: true }),
  n("buwan", "moon", "nature", "thing", { noObj: true }),
  n("bituin", "star", "nature", "thing", { noObj: true }),
  n("dahon", "leaf", "nature", "thing", { pl: "leaves" }),
  n("bato", "stone", "nature", "thing"),
  n("langit", "sky", "nature", "place", { pl: "skies" }),
  n("gubat", "forest", "nature", "place"),
  n("talon", "waterfall", "nature", "place"),

  // ---- weather ----
  n("ulan", "rain", "weather", "abstract", { mass: true }),
  n("init", "heat", "weather", "abstract", { mass: true }),
  n("lamig", "cold", "weather", "abstract", { mass: true }),
  n("bagyo", "typhoon", "weather", "abstract"),
  n("hangin", "wind", "weather", "abstract", { mass: true }),
  n("kidlat", "lightning", "weather", "abstract", { mass: true }),
  n("kulog", "thunder", "weather", "abstract", { mass: true }),
  n("baha", "flood", "weather", "abstract"),
  n("tag-init", "summer", "weather", "abstract", { mass: true }),
  n("tag-ulan", "rainy season", "weather", "abstract", { mass: true }),
  n("panahon", "weather", "weather", "abstract", { mass: true }),
  n("hamog", "dew", "weather", "abstract", { mass: true }),

  // ---- animals ----
  n("aso", "dog", "animals", "animal"),
  n("pusa", "cat", "animals", "animal"),
  n("ibon", "bird", "animals", "animal"),
  n("kalabaw", "water buffalo", "animals", "animal"),
  n("kambing", "goat", "animals", "animal"),
  n("daga", "rat", "animals", "animal"),
  n("ahas", "snake", "animals", "animal"),
  n("kabayo", "horse", "animals", "animal"),
  n("unggoy", "monkey", "animals", "animal", { pl: "monkeys" }),
  n("pagong", "turtle", "animals", "animal"),
  n("palaka", "frog", "animals", "animal"),
  n("butiki", "lizard", "animals", "animal"),

  // ---- sea ----
  n("buhangin", "sand", "sea", "thing", { mass: true }),
  n("alon", "wave", "sea", "thing", { noObj: true }),
  n("hipon", "shrimp", "sea", "food", { pl: "shrimp" }),
  n("alimango", "crab", "sea", "food"),
  n("pusit", "squid", "sea", "food", { pl: "squid" }),
  n("tahong", "mussel", "sea", "food"),
  n("baybayin", "shore", "sea", "place"),
  n("korales", "coral", "sea", "thing", { mass: true , noObj: true }),
  n("lambat", "net", "sea", "thing"),
  n("pating", "shark", "sea", "animal"),
  n("dolphin", "dolphin", "sea", "animal"),
  n("bakawan", "mangrove", "sea", "thing", { noObj: true }),

  // ---- insects ----
  n("langgam", "ant", "insects", "animal"),
  n("lamok", "mosquito", "insects", "animal", { pl: "mosquitoes" }),
  n("ipis", "cockroach", "insects", "animal", { pl: "cockroaches" }),
  n("gagamba", "spider", "insects", "animal"),
  n("paruparo", "butterfly", "insects", "animal", { pl: "butterflies" }),
  n("bubuyog", "bee", "insects", "animal"),
  n("tutubi", "dragonfly", "insects", "animal", { pl: "dragonflies" }),
  n("langaw", "fly", "insects", "animal", { pl: "flies" }),
  n("kuliglig", "cricket", "insects", "animal"),
  n("uod", "worm", "insects", "animal"),
  n("alupihan", "centipede", "insects", "animal"),
  n("anay", "termite", "insects", "animal"),

  // ---- sports ----
  n("basketbol", "basketball", "sports", "abstract", { mass: true }),
  n("bola", "ball", "sports", "thing"),
  n("laro", "game", "sports", "abstract"),
  n("koponan", "team", "sports", "person"),
  n("manlalaro", "player", "sports", "person"),
  n("takbuhan", "race", "sports", "abstract"),
  n("kampeon", "champion", "sports", "person"),
  n("boksing", "boxing", "sports", "abstract", { mass: true }),
  n("badminton", "badminton", "sports", "abstract", { mass: true }),
  n("iskor", "score", "sports", "abstract"),
  n("korte", "court", "sports", "place"),
  n("medalya", "medal", "sports", "thing"),

  // ---- hobbies ----
  n("libangan", "hobby", "hobbies", "abstract", { pl: "hobbies" }),
  n("pelikula", "movie", "hobbies", "thing"),
  n("kanta", "song", "hobbies", "thing"),
  n("sayaw", "dance", "hobbies", "abstract"),
  n("gitara", "guitar", "hobbies", "thing"),
  n("kuwento", "story", "hobbies", "thing", { pl: "stories" }),
  n("tula", "poem", "hobbies", "thing"),
  n("baraha", "playing cards", "hobbies", "thing"),
  n("kamera", "camera", "hobbies", "thing"),
  n("pintura", "paint", "hobbies", "thing", { mass: true }),
  n("koleksiyon", "collection", "hobbies", "abstract"),
  n("hardinero", "gardener", "hobbies", "person"),

  // ---- music ----
  n("musika", "music", "music", "abstract", { mass: true }),
  n("tugtog", "tune", "music", "thing"),
  n("banda", "band", "music", "person"),
  n("mikropono", "microphone", "music", "thing"),
  n("tambol", "drum", "music", "thing"),
  n("boses", "voice", "music", "abstract", { pl: "voices" }),
  n("konsiyerto", "concert", "music", "abstract"),
  n("mang-aawit", "singer", "music", "person"),
  n("piyano", "piano", "music", "thing"),
  n("plawta", "flute", "music", "thing"),
  n("himig", "melody", "music", "thing", { pl: "melodies" }),
  n("koro", "choir", "music", "person"),

  // ---- money ----
  n("pera", "money", "money", "thing", { mass: true }),
  n("piso", "peso", "money", "thing"),
  n("barya", "coin", "money", "thing"),
  n("diskwento", "discount", "money", "abstract"),
  n("pitaka", "wallet", "money", "thing"),
  n("utang", "debt", "money", "abstract"),
  n("sukli", "change", "money", "thing", { mass: true }),
  n("bayad", "payment", "money", "abstract"),
  n("ipon", "savings", "money", "abstract", { pl: "savings" }),
  n("gastos", "expense", "money", "abstract"),
  n("kita", "income", "money", "abstract", { mass: true }),
  n("buwis", "tax", "money", "abstract", { pl: "taxes" }),

  // ---- time ----
  n("oras", "hour", "time", "abstract"),
  n("araw", "day", "time", "abstract"),
  n("linggo", "week", "time", "abstract"),
  n("taon", "year", "time", "abstract"),
  n("umaga", "morning", "time", "abstract"),
  n("tanghali", "noon", "time", "abstract", { mass: true }),
  n("hapon", "afternoon", "time", "abstract"),
  n("gabi", "night", "time", "abstract"),
  n("minuto", "minute", "time", "abstract"),
  n("sandali", "moment", "time", "abstract"),
  n("kalendaryo", "calendar", "time", "thing"),
  n("petsa", "date", "time", "abstract"),

  // ---- celebrations ----
  n("kaarawan", "birthday", "celebrations", "abstract"),
  n("pista", "fiesta", "celebrations", "abstract"),
  n("Pasko", "Christmas", "celebrations", "abstract", { proper: true }),
  n("kasal", "wedding", "celebrations", "abstract"),
  n("handaan", "feast", "celebrations", "abstract"),
  n("regalo", "gift", "celebrations", "thing"),
  n("keyk", "cake", "celebrations", "food"),
  n("parol", "Christmas lantern", "celebrations", "thing"),
  n("kandila", "candle", "celebrations", "thing"),
  n("palamuti", "decoration", "celebrations", "thing"),
  n("imbitasyon", "invitation", "celebrations", "thing"),
  n("prusisyon", "procession", "celebrations", "abstract"),

  // ---- feelings ----
  n("saya", "joy", "feelings", "abstract", { mass: true }),
  n("lungkot", "sadness", "feelings", "abstract", { mass: true }),
  n("galit", "anger", "feelings", "abstract", { mass: true }),
  n("takot", "fear", "feelings", "abstract", { mass: true }),
  n("gutom", "hunger", "feelings", "abstract", { mass: true }),
  n("uhaw", "thirst", "feelings", "abstract", { mass: true }),
  n("pagod", "tiredness", "feelings", "abstract", { mass: true }),
  n("hiya", "shame", "feelings", "abstract", { mass: true }),
  n("pag-asa", "hope", "feelings", "abstract", { mass: true }),
  n("inggit", "envy", "feelings", "abstract", { mass: true }),
  n("tiwala", "trust", "feelings", "abstract", { mass: true }),
  n("damdamin", "feeling", "feelings", "abstract"),

  // ---- relationships ----
  n("nobyo", "boyfriend", "relationships", "person"),
  n("nobya", "girlfriend", "relationships", "person"),
  n("pag-ibig", "love", "relationships", "abstract", { mass: true }),
  n("halik", "kiss", "relationships", "abstract", { pl: "kisses" }),
  n("yakap", "hug", "relationships", "abstract"),
  n("pangako", "promise", "relationships", "abstract"),
  n("away", "quarrel", "relationships", "abstract"),
  n("alaala", "memory", "relationships", "abstract", { pl: "memories" }),
  n("sulat", "letter", "relationships", "thing"),
  n("petsahan", "date", "relationships", "abstract"),
  n("singsing", "ring", "relationships", "thing"),
  n("panganay", "eldest child", "relationships", "person"),

  // ---- phone ----
  n("telepono", "telephone", "phone", "thing"),
  n("numero", "number", "phone", "abstract"),
  n("load", "phone credit", "phone", "abstract", { mass: true }),
  n("sagot", "answer", "phone", "abstract"),
  n("linya", "line", "phone", "abstract"),
  n("boses", "voice", "phone", "abstract", { pl: "voices" }),
  n("miskol", "missed call", "phone", "abstract"),
  n("text", "text", "phone", "thing"),
  n("kausap", "person on the line", "phone", "person"),
  n("ringtone", "ringtone", "phone", "thing"),
  n("headset", "headset", "phone", "thing"),
  n("tono", "tone", "phone", "abstract"),

  // ---- chores ----
  n("labada", "laundry", "chores", "thing", { mass: true }),
  n("plantsa", "iron", "chores", "thing"),
  n("walis", "broom", "chores", "thing"),
  n("basura", "trash", "chores", "thing", { mass: true }),
  n("sabon", "soap", "chores", "thing", { mass: true }),
  n("pinggan", "dish", "chores", "thing", { pl: "dishes" }),
  n("timba", "pail", "chores", "thing"),
  n("basahan", "rag", "chores", "thing"),
  n("alikabok", "dust", "chores", "thing", { mass: true }),
  n("gamit", "belongings", "chores", "thing", { pl: "belongings" }),
  n("sampayan", "clothesline", "chores", "thing"),
  n("almusalan", "dining area", "chores", "place"),

  // ---- faith ----
  n("misa", "mass", "faith", "abstract", { pl: "masses" }),
  n("dasal", "prayer", "faith", "abstract"),
  n("pari", "priest", "faith", "person"),
  n("Diyos", "God", "faith", "person", { proper: true }),
  n("bibliya", "bible", "faith", "thing"),
  n("pananampalataya", "faith", "faith", "abstract", { mass: true }),
  n("awit", "hymn", "faith", "thing"),
  n("santo", "saint", "faith", "person"),
  n("kapilya", "chapel", "faith", "place"),
  n("krus", "cross", "faith", "thing", { pl: "crosses" }),
  n("altar", "altar", "faith", "thing"),
  n("binyag", "baptism", "faith", "abstract"),

  // ---- farm ----
  n("bukid", "farm", "farm", "place"),
  n("palay", "rice plant", "farm", "thing", { mass: true }),
  n("ani", "harvest", "farm", "abstract"),
  n("araro", "plow", "farm", "thing"),
  n("binhi", "seed", "farm", "thing"),
  n("lupa", "soil", "farm", "thing", { mass: true }),
  n("damo", "grass", "farm", "thing", { mass: true }),
  n("kamalig", "barn", "farm", "place"),
  n("itik", "duck", "farm", "animal"),
  n("baka", "cow", "farm", "animal"),
  n("tubo", "sugarcane", "farm", "thing", { mass: true }),
  n("niyog", "coconut", "farm", "food"),

  // ---- neighborhood ----
  n("barangay", "barangay", "neighborhood", "place"),
  n("kapitan", "barangay captain", "neighborhood", "person"),
  n("ingay", "noise", "neighborhood", "abstract", { mass: true }),
  n("eskinita", "alley", "neighborhood", "place"),
  n("poste", "post", "neighborhood", "thing", { noObj: true }),
  n("gate", "gate", "neighborhood", "thing", { noObj: true }),
  n("sari-sari store", "sundry store", "neighborhood", "place"),
  n("bantay", "guard", "neighborhood", "person"),
  n("kapilyahan", "neighborhood chapel", "neighborhood", "place"),
  n("kapistahan", "town fiesta", "neighborhood", "abstract"),
  n("basketbolan", "basketball court", "neighborhood", "place"),
  n("kanal", "canal", "neighborhood", "place"),

  // ---- services ----
  n("susi", "key", "services", "thing"),
  n("resepsiyon", "reception", "services", "place"),
  n("tuwalya", "towel", "services", "thing"),
  n("serbisyo", "service", "services", "abstract"),
  n("reklamo", "complaint", "services", "abstract"),
  n("pila", "queue", "services", "abstract"),
  n("pirma", "signature", "services", "thing"),
  n("porma", "form", "services", "thing"),
  n("koreo", "post office", "services", "place"),
  n("parsela", "parcel", "services", "thing"),
  n("kard", "card", "services", "thing"),
];

/** every place-like noun, for "sa <place>" templates */
export const PLACES = NOUNS.filter((x) => x.cat === "place");
/** people, for third-person subjects */
export const PEOPLE = NOUNS.filter((x) => x.cat === "person" && !x.proper);

// ---------------------------------------------------------------------- verbs

const v = (id, f, en, opts = {}) => ({ id, f, en, obj: null, loc: false, ...opts });

export const VERBS = [
  v("kain", { inf: "kumain", comp: "kumain", prog: "kumakain", cont: "kakain", imp: "kumain" },
    { base: "eat", s: "eats", ing: "eating", past: "ate" },
    { obj: ["food"], o: { inf: "kainin", comp: "kinain", prog: "kinakain", cont: "kakainin" } }),
  v("inom", { inf: "uminom", comp: "uminom", prog: "umiinom", cont: "iinom", imp: "uminom" },
    { base: "drink", s: "drinks", ing: "drinking", past: "drank" },
    { obj: ["drink"], o: { inf: "inumin", comp: "ininom", prog: "iniinom", cont: "iinumin" } }),
  v("bili", { inf: "bumili", comp: "bumili", prog: "bumibili", cont: "bibili", imp: "bumili" },
    { base: "buy", s: "buys", ing: "buying", past: "bought" },
    { obj: ["food", "drink", "thing"], o: { inf: "bilhin", comp: "binili", prog: "binibili", cont: "bibilhin" }, loc: true }),
  v("luto", { inf: "magluto", comp: "nagluto", prog: "nagluluto", cont: "magluluto", imp: "magluto" },
    { base: "cook", s: "cooks", ing: "cooking", past: "cooked" },
    { obj: ["food"], o: { inf: "lutuin", comp: "niluto", prog: "niluluto", cont: "lulutuin" } }),
  v("punta", { inf: "pumunta", comp: "pumunta", prog: "pumupunta", cont: "pupunta", imp: "pumunta" },
    { base: "go", s: "goes", ing: "going", past: "went" }, { loc: true, locOnly: true }),
  v("alis", { inf: "umalis", comp: "umalis", prog: "umaalis", cont: "aalis", imp: "umalis" },
    { base: "leave", s: "leaves", ing: "leaving", past: "left" }),
  v("uwi", { inf: "umuwi", comp: "umuwi", prog: "umuuwi", cont: "uuwi", imp: "umuwi" },
    { base: "go home", s: "goes home", ing: "going home", past: "went home" }),
  v("dating", { inf: "dumating", comp: "dumating", prog: "dumarating", cont: "darating", imp: "dumating" },
    { base: "arrive", s: "arrives", ing: "arriving", past: "arrived" }),
  v("tulog", { inf: "matulog", comp: "natulog", prog: "natutulog", cont: "matutulog", imp: "matulog" },
    { base: "sleep", s: "sleeps", ing: "sleeping", past: "slept" }),
  v("gising", { inf: "gumising", comp: "gumising", prog: "gumigising", cont: "gigising", imp: "gumising" },
    { base: "wake up", s: "wakes up", ing: "waking up", past: "woke up" }),
  v("takbo", { inf: "tumakbo", comp: "tumakbo", prog: "tumatakbo", cont: "tatakbo", imp: "tumakbo" },
    { base: "run", s: "runs", ing: "running", past: "ran" }),
  v("lakad", { inf: "lumakad", comp: "lumakad", prog: "lumalakad", cont: "lalakad", imp: "lumakad" },
    { base: "walk", s: "walks", ing: "walking", past: "walked" }),
  v("upo", { inf: "umupo", comp: "umupo", prog: "umuupo", cont: "uupo", imp: "umupo" },
    { base: "sit", s: "sits", ing: "sitting", past: "sat" }),
  v("tayo", { inf: "tumayo", comp: "tumayo", prog: "tumatayo", cont: "tatayo", imp: "tumayo" },
    { base: "stand", s: "stands", ing: "standing", past: "stood" }),
  v("basa", { inf: "bumasa", comp: "bumasa", prog: "bumabasa", cont: "babasa", imp: "bumasa" },
    { base: "read", s: "reads", ing: "reading", past: "read" },
    { obj: ["thing"], o: { inf: "basahin", comp: "binasa", prog: "binabasa", cont: "babasahin" } , objIds: ["libro","sulat","kuwento","tula","ulat","mensahe","email","bibliya","menu","listahan","kuwaderno","aralin","resipe","imbitasyon","teksto","text"] }),  v("sulat", { inf: "sumulat", comp: "sumulat", prog: "sumusulat", cont: "susulat", imp: "sumulat" },
    { base: "write", s: "writes", ing: "writing", past: "wrote" },
    { obj: ["thing"], o: { inf: "sulatin", comp: "sinulat", prog: "sinusulat", cont: "susulatin" } , objIds: ["sulat","kuwento","tula","ulat","mensahe","email","listahan","imbitasyon","aralin","takdang-aralin"] }),  v("kanta", { inf: "kumanta", comp: "kumanta", prog: "kumakanta", cont: "kakanta", imp: "kumanta" },
    { base: "sing", s: "sings", ing: "singing", past: "sang" }),
  v("sayaw", { inf: "sumayaw", comp: "sumayaw", prog: "sumasayaw", cont: "sasayaw", imp: "sumayaw" },
    { base: "dance", s: "dances", ing: "dancing", past: "danced" }),
  v("tawa", { inf: "tumawa", comp: "tumawa", prog: "tumatawa", cont: "tatawa", imp: "tumawa" },
    { base: "laugh", s: "laughs", ing: "laughing", past: "laughed" }),
  v("iyak", { inf: "umiyak", comp: "umiyak", prog: "umiiyak", cont: "iiyak", imp: "umiyak" },
    { base: "cry", s: "cries", ing: "crying", past: "cried" }),
  v("ligo", { inf: "maligo", comp: "naligo", prog: "naliligo", cont: "maliligo", imp: "maligo" },
    { base: "take a bath", s: "takes a bath", ing: "taking a bath", past: "took a bath" }),
  v("laba", { inf: "maglaba", comp: "naglaba", prog: "naglalaba", cont: "maglalaba", imp: "maglaba" },
    { base: "do the laundry", s: "does the laundry", ing: "doing the laundry", past: "did the laundry" }),
  v("linis", { inf: "maglinis", comp: "naglinis", prog: "naglilinis", cont: "maglilinis", imp: "maglinis" },
    { base: "clean", s: "cleans", ing: "cleaning", past: "cleaned" },
    { o: { inf: "linisin", comp: "nilinis", prog: "nililinis", cont: "lilinisin" }, obj: ["place", "thing"] }),
  v("aral", { inf: "mag-aral", comp: "nag-aral", prog: "nag-aaral", cont: "mag-aaral", imp: "mag-aral" },
    { base: "study", s: "studies", ing: "studying", past: "studied" }),
  v("trabaho", { inf: "magtrabaho", comp: "nagtrabaho", prog: "nagtatrabaho", cont: "magtatrabaho", imp: "magtrabaho" },
    { base: "work", s: "works", ing: "working", past: "worked" }),
  v("laro", { inf: "maglaro", comp: "naglaro", prog: "naglalaro", cont: "maglalaro", imp: "maglaro" },
    { base: "play", s: "plays", ing: "playing", past: "played" }),
  v("bayad", { inf: "magbayad", comp: "nagbayad", prog: "nagbabayad", cont: "magbabayad", imp: "magbayad" },
    { base: "pay", s: "pays", ing: "paying", past: "paid" }),
  v("salita", { inf: "magsalita", comp: "nagsalita", prog: "nagsasalita", cont: "magsasalita", imp: "magsalita" },
    { base: "speak", s: "speaks", ing: "speaking", past: "spoke" }),
  v("hintay", { inf: "maghintay", comp: "naghintay", prog: "naghihintay", cont: "maghihintay", imp: "maghintay" },
    { base: "wait", s: "waits", ing: "waiting", past: "waited" }),
  v("dala", { inf: "magdala", comp: "nagdala", prog: "nagdadala", cont: "magdadala", imp: "magdala" },
    { base: "bring", s: "brings", ing: "bringing", past: "brought" },
    { obj: ["thing", "food", "drink"], o: { inf: "dalhin", comp: "dinala", prog: "dinadala", cont: "dadalhin" } , objIds: ["payong","bag","libro","tubig","regalo","gamot","kamera","susi","pitaka","tiket","bagahe","keyk","pera","selpon","tsarger","kape","meryenda","tinapay","tuwalya","bibliya","kuwaderno","bolpen"] }),  v("bigay", { inf: "magbigay", comp: "nagbigay", prog: "nagbibigay", cont: "magbibigay", imp: "magbigay" },
    { base: "give", s: "gives", ing: "giving", past: "gave" }, { obj: ["thing", "food"] , objIds: ["regalo","pera","tinapay","bulaklak","sulat","gamot","keyk","libro","kape","meryenda","prutas","tiket","kard","singsing","kuwintas","imbitasyon","tsokolate","bitamina","sorbetes","medalya"] }),  v("kuha", { inf: "kumuha", comp: "kumuha", prog: "kumukuha", cont: "kukuha", imp: "kumuha" },
    { base: "get", s: "gets", ing: "getting", past: "got" },
    { obj: ["thing", "food", "drink"], o: { inf: "kunin", comp: "kinuha", prog: "kinukuha", cont: "kukunin" } }),
  v("hanap", { inf: "maghanap", comp: "naghanap", prog: "naghahanap", cont: "maghahanap", imp: "maghanap" },
    { base: "look for", s: "looks for", ing: "looking for", past: "looked for" },
    { obj: ["thing", "person"], o: { inf: "hanapin", comp: "hinanap", prog: "hinahanap", cont: "hahanapin" } }),
  v("tanong", { inf: "magtanong", comp: "nagtanong", prog: "nagtatanong", cont: "magtatanong", imp: "magtanong" },
    { base: "ask", s: "asks", ing: "asking", past: "asked" }),
  v("sagot", { inf: "sumagot", comp: "sumagot", prog: "sumasagot", cont: "sasagot", imp: "sumagot" },
    { base: "answer", s: "answers", ing: "answering", past: "answered" }),
  v("tawag", { inf: "tumawag", comp: "tumawag", prog: "tumatawag", cont: "tatawag", imp: "tumawag" },
    { base: "call", s: "calls", ing: "calling", past: "called" }),
  v("panood", { inf: "manood", comp: "nanood", prog: "nanonood", cont: "manonood", imp: "manood" },
    { base: "watch", s: "watches", ing: "watching", past: "watched" }, { obj: ["thing"] , objIds: ["pelikula","bidyo","laro","sayaw","konsiyerto","basketbol","boksing","badminton","tugtog","prusisyon","misa","palaro"] }),  v("kinig", { inf: "makinig", comp: "nakinig", prog: "nakikinig", cont: "makikinig", imp: "makinig" },
    { base: "listen", s: "listens", ing: "listening", past: "listened" }),
  v("gawa", { inf: "gumawa", comp: "gumawa", prog: "gumagawa", cont: "gagawa", imp: "gumawa" },
    { base: "make", s: "makes", ing: "making", past: "made" },
    { obj: ["thing", "food"], o: { inf: "gawin", comp: "ginawa", prog: "ginagawa", cont: "gagawin" } , objIds: ["keyk","kape","tinapay","sopas","ulat","listahan","palamuti","resipe","guhit","tula","kuwento","adobo","sinigang","pansit","proyekto","imbitasyon","parol","kandila","lugaw"] }),  v("bukas", { inf: "magbukas", comp: "nagbukas", prog: "nagbubukas", cont: "magbubukas", imp: "magbukas" },
    { base: "open", s: "opens", ing: "opening", past: "opened" },
    { obj: ["thing"], o: { inf: "buksan", comp: "binuksan", prog: "binubuksan", cont: "bubuksan" } , objIds: ["pinto","bintana","bote","aparador","ilaw","kompyuter","selpon","libro","kurtina","gate","takip","susi"] }),  v("sara", { inf: "magsara", comp: "nagsara", prog: "nagsasara", cont: "magsasara", imp: "magsara" },
    { base: "close", s: "closes", ing: "closing", past: "closed" },
    { obj: ["thing"], o: { inf: "isara", comp: "isinara", prog: "isinasara", cont: "isasara" } , objIds: ["pinto","bintana","bote","aparador","ilaw","kompyuter","selpon","libro","kurtina","gate","takip"] }),  v("sakay", { inf: "sumakay", comp: "sumakay", prog: "sumasakay", cont: "sasakay", imp: "sumakay" },
    { base: "ride", s: "rides", ing: "riding", past: "rode" }),
  v("baba", { inf: "bumaba", comp: "bumaba", prog: "bumababa", cont: "bababa", imp: "bumaba" },
    { base: "go down", s: "goes down", ing: "going down", past: "went down" }),
  v("akyat", { inf: "umakyat", comp: "umakyat", prog: "umaakyat", cont: "aakyat", imp: "umakyat" },
    { base: "climb", s: "climbs", ing: "climbing", past: "climbed" }),
  v("pasok", { inf: "pumasok", comp: "pumasok", prog: "pumapasok", cont: "papasok", imp: "pumasok" },
    { base: "go in", s: "goes in", ing: "going in", past: "went in" }, { loc: true }),
  v("labas", { inf: "lumabas", comp: "lumabas", prog: "lumalabas", cont: "lalabas", imp: "lumabas" },
    { base: "go out", s: "goes out", ing: "going out", past: "went out" }),
  v("balik", { inf: "bumalik", comp: "bumalik", prog: "bumabalik", cont: "babalik", imp: "bumalik" },
    { base: "come back", s: "comes back", ing: "coming back", past: "came back" }, { loc: true }),
  v("hiram", { inf: "humiram", comp: "humiram", prog: "humihiram", cont: "hihiram", imp: "humiram" },
    { base: "borrow", s: "borrows", ing: "borrowing", past: "borrowed" },
    { obj: ["thing"], o: { inf: "hiramin", comp: "hiniram", prog: "hinihiram", cont: "hihiramin" } , objIds: ["libro","bolpen","payong","kotse","gitara","lapis","kuwaderno","bisikleta","kamera","susi","pitaka"] }),  v("tulong", { inf: "tumulong", comp: "tumulong", prog: "tumutulong", cont: "tutulong", imp: "tumulong" },
    { base: "help", s: "helps", ing: "helping", past: "helped" }),
  v("turo", { inf: "magturo", comp: "nagturo", prog: "nagtuturo", cont: "magtuturo", imp: "magturo" },
    { base: "teach", s: "teaches", ing: "teaching", past: "taught" }),
  v("bilang", { inf: "magbilang", comp: "nagbilang", prog: "nagbibilang", cont: "magbibilang", imp: "magbilang" },
    { base: "count", s: "counts", ing: "counting", past: "counted" }),
  v("ayos", { inf: "mag-ayos", comp: "nag-ayos", prog: "nag-aayos", cont: "mag-aayos", imp: "mag-ayos" },
    { base: "tidy up", s: "tidies up", ing: "tidying up", past: "tidied up" }),
  v("hugas", { inf: "maghugas", comp: "naghugas", prog: "naghuhugas", cont: "maghuhugas", imp: "maghugas" },
    { base: "wash", s: "washes", ing: "washing", past: "washed" },
    { obj: ["thing"], o: { inf: "hugasan", comp: "hinugasan", prog: "hinuhugasan", cont: "huhugasan" } , objIds: ["pinggan","plato","baso","kamay","damit","gulay","prutas","kutsara","tinidor","mangkok","kaldero","kawali","basahan"] }),  v("walis", { inf: "magwalis", comp: "nagwalis", prog: "nagwawalis", cont: "magwawalis", imp: "magwalis" },
    { base: "sweep", s: "sweeps", ing: "sweeping", past: "swept" }),
  v("plantsa", { inf: "magplantsa", comp: "nagplantsa", prog: "nagpaplantsa", cont: "magpaplantsa", imp: "magplantsa" },
    { base: "iron clothes", s: "irons clothes", ing: "ironing clothes", past: "ironed clothes" }),
  v("tapon", { inf: "magtapon", comp: "nagtapon", prog: "nagtatapon", cont: "magtatapon", imp: "magtapon" },
    { base: "throw away", s: "throws away", ing: "throwing away", past: "threw away" },
    { obj: ["thing"], o: { inf: "itapon", comp: "itinapon", prog: "itinatapon", cont: "itatapon" } , objIds: ["basura","alikabok","supot","bote","papel","gamit","tisyu","balat","damo"] }),  v("simula", { inf: "magsimula", comp: "nagsimula", prog: "nagsisimula", cont: "magsisimula", imp: "magsimula" },
    { base: "start", s: "starts", ing: "starting", past: "started" }),
  v("ngiti", { inf: "ngumiti", comp: "ngumiti", prog: "ngumingiti", cont: "ngingiti", imp: "ngumiti" },
    { base: "smile", s: "smiles", ing: "smiling", past: "smiled" }),
  v("yakap", { inf: "yumakap", comp: "yumakap", prog: "yumayakap", cont: "yayakap", imp: "yumakap" },
    { base: "hug", s: "hugs", ing: "hugging", past: "hugged" }),
  v("bisita", { inf: "bumisita", comp: "bumisita", prog: "bumibisita", cont: "bibisita", imp: "bumisita" },
    { base: "visit", s: "visits", ing: "visiting", past: "visited" }, { loc: true }),
  v("pili", { inf: "pumili", comp: "pumili", prog: "pumipili", cont: "pipili", imp: "pumili" },
    { base: "choose", s: "chooses", ing: "choosing", past: "chose" },
    { obj: ["thing", "food"], o: { inf: "piliin", comp: "pinili", prog: "pinipili", cont: "pipiliin" } }),
  v("tira", { inf: "tumira", comp: "tumira", prog: "tumitira", cont: "titira", imp: "tumira" },
    { base: "live", s: "lives", ing: "living", past: "lived" }, { loc: true, locOnly: true }),
  v("higa", { inf: "humiga", comp: "humiga", prog: "humihiga", cont: "hihiga", imp: "humiga" },
    { base: "lie down", s: "lies down", ing: "lying down", past: "lay down" }),
  v("sundo", { inf: "sumundo", comp: "sumundo", prog: "sumusundo", cont: "susundo", imp: "sumundo" },
    { base: "pick up", s: "picks up", ing: "picking up", past: "picked up" }),
  v("hatid", { inf: "maghatid", comp: "naghatid", prog: "naghahatid", cont: "maghahatid", imp: "maghatid" },
    { base: "deliver", s: "delivers", ing: "delivering", past: "delivered" }, { obj: ["thing", "food"] , objIds: ["parsela","sulat","order","tinapay","gamot","mensahe","pagkain","keyk","regalo","meryenda","kard"] }),  v("lagay", { inf: "maglagay", comp: "naglagay", prog: "naglalagay", cont: "maglalagay", imp: "maglagay" },
    { base: "put", s: "puts", ing: "putting", past: "put" },
    { obj: ["thing", "food"], o: { inf: "ilagay", comp: "inilagay", prog: "inilalagay", cont: "ilalagay" } , objIds: ["asin","asukal","yelo","gamot","pera","libro","damit","plato","sabon","mantika","palaman","unan","kumot","bulaklak","kandila","keso","mantikilya","luya","bawang","pintura"] }),  v("isip", { inf: "mag-isip", comp: "nag-isip", prog: "nag-iisip", cont: "mag-iisip", imp: "mag-isip" },
    { base: "think", s: "thinks", ing: "thinking", past: "thought" }),
  v("dasal", { inf: "magdasal", comp: "nagdasal", prog: "nagdarasal", cont: "magdarasal", imp: "magdasal" },
    { base: "pray", s: "prays", ing: "praying", past: "prayed" }),
  v("tanim", { inf: "magtanim", comp: "nagtanim", prog: "nagtatanim", cont: "magtatanim", imp: "magtanim" },
    { base: "plant", s: "plants", ing: "planting", past: "planted" }, { obj: ["thing", "food"] , objIds: ["binhi","palay","gulay","bulaklak","puno","mais","kamatis","talong","sitaw","luya","tubo","niyog","damo"] }),  v("ani", { inf: "mag-ani", comp: "nag-ani", prog: "nag-aani", cont: "mag-aani", imp: "mag-ani" },
    { base: "harvest", s: "harvests", ing: "harvesting", past: "harvested" }, { obj: ["food"] , objIds: ["palay","mais","gulay","prutas","niyog","tubo","saging","mangga","kalabasa","kamatis"] }),  v("benta", { inf: "magbenta", comp: "nagbenta", prog: "nagbebenta", cont: "magbebenta", imp: "magbenta" },
    { base: "sell", s: "sells", ing: "selling", past: "sold" }, { obj: ["food", "thing", "drink"] , objIds: ["isda","gulay","prutas","tinapay","kape","damit","sapatos","bulaklak","keyk","meryenda","sorbetes","manok","itlog","bigas","mangga","saging","pansit","juice","softdrink","gatas"] }),  v("langoy", { inf: "lumangoy", comp: "lumangoy", prog: "lumalangoy", cont: "lalangoy", imp: "lumangoy" },
    { base: "swim", s: "swims", ing: "swimming", past: "swam" }),
  v("sakit", { inf: "magkasakit", comp: "nagkasakit", prog: "nagkakasakit", cont: "magkakasakit", imp: "magkasakit" },
    { base: "get sick", s: "gets sick", ing: "getting sick", past: "got sick" }),
  v("bihis", { inf: "magbihis", comp: "nagbihis", prog: "nagbibihis", cont: "magbibihis", imp: "magbihis" },
    { base: "get dressed", s: "gets dressed", ing: "getting dressed", past: "got dressed" }),
  v("kuwento", { inf: "magkuwento", comp: "nagkuwento", prog: "nagkukuwento", cont: "magkukuwento", imp: "magkuwento" },
    { base: "tell a story", s: "tells a story", ing: "telling a story", past: "told a story" }),
  v("sayang", { inf: "magsaya", comp: "nagsaya", prog: "nagsasaya", cont: "magsasaya", imp: "magsaya" },
    { base: "have fun", s: "has fun", ing: "having fun", past: "had fun" }),
  v("handa", { inf: "maghanda", comp: "naghanda", prog: "naghahanda", cont: "maghahanda", imp: "maghanda" },
    { base: "prepare", s: "prepares", ing: "preparing", past: "prepared" }, { obj: ["food", "thing"] , objIds: ["pagkain","almusal","hapunan","tanghalian","keyk","handaan","mesa","kape","sopas","adobo","meryenda","ulat","pulong","sinigang","pansit","biyahe","bagahe","order"] }),  v("sukat", { inf: "magsukat", comp: "nagsukat", prog: "nagsusukat", cont: "magsusukat", imp: "magsukat" },
    { base: "try on", s: "tries on", ing: "trying on", past: "tried on" }, { obj: ["thing"] , objIds: ["damit","sapatos","bestida","palda","pantalon","sumbrero","tsinelas","medyas","dyaket","kamiseta","singsing","relo"] }),  v("ipon", { inf: "mag-ipon", comp: "nag-ipon", prog: "nag-iipon", cont: "mag-iipon", imp: "mag-ipon" },
    { base: "save up", s: "saves up", ing: "saving up", past: "saved up" }, { obj: ["thing"] , objIds: ["pera","barya","piso","sukli","ipon","gastos","buwis","kita"] }),];

export const VERB = Object.fromEntries(VERBS.map((x) => [x.id, x]));
/** verbs that can take a direct object of some category */
export const TRANSITIVE = VERBS.filter((x) => x.obj);
/** verbs with a full object-focus paradigm */
export const OBJECT_FOCUS = VERBS.filter((x) => x.o);
/** verbs that read naturally with "sa <place>" */
export const MOTION = VERBS.filter((x) => x.loc);

// ----------------------------------------------------------------- adjectives

const a = (tl, en, opts = {}) => ({ tl, en, fits: ["thing"], ...opts });

export const ADJECTIVES = [
  a("masarap", "delicious", { fits: ["food", "drink"] }),
  a("matamis", "sweet", { fits: ["food", "drink"] }),
  a("maalat", "salty", { fits: ["food"] }),
  a("maasim", "sour", { fits: ["food"] }),
  a("maanghang", "spicy", { fits: ["food"] }),
  a("mapait", "bitter", { fits: ["food", "drink"] }),
  a("sariwa", "fresh", { fits: ["food"] }),
  a("mainit", "hot", { fits: ["food", "drink", "thing", "place", "abstract"] }),
  a("malamig", "cold", { fits: ["food", "drink", "thing", "place", "abstract"] }),
  a("malaki", "big", { fits: ["thing", "place", "animal", "person", "food"] }),
  a("maliit", "small", { fits: ["thing", "place", "animal", "person", "food"] }),
  a("mahaba", "long", { fits: ["thing", "bodypart"] }),
  a("maikli", "short", { fits: ["thing", "bodypart"] }),
  a("mataas", "tall", { fits: ["thing", "place", "person"] }),
  a("mababa", "low", { fits: ["thing", "place"] }),
  a("mabigat", "heavy", { fits: ["thing"] }),
  a("magaan", "light", { fits: ["thing"] }),
  a("maganda", "beautiful", { fits: ["thing", "place", "person", "abstract"] }),
  a("pangit", "ugly", { fits: ["thing", "place"] }),
  a("mabait", "kind", { fits: ["person", "animal"] }),
  a("masama", "bad", { fits: ["thing", "abstract", "person"] }),
  a("mabuti", "good", { fits: ["thing", "abstract", "person"] }),
  a("masaya", "happy", { fits: ["person", "abstract", "place"] }),
  a("malungkot", "sad", { fits: ["person", "abstract"] }),
  a("mahal", "expensive", { fits: ["thing", "food", "drink"] }),
  a("mura", "cheap", { fits: ["thing", "food", "drink"] }),
  a("bago", "new", { fits: ["thing", "place"] }),
  a("luma", "old", { fits: ["thing", "place"] }),
  a("matanda", "old", { fits: ["person", "animal"] }),
  a("bata", "young", { fits: ["person", "animal"] }),
  a("mabilis", "fast", { fits: ["thing", "person", "animal"] }),
  a("mabagal", "slow", { fits: ["thing", "person", "animal"] }),
  a("malinis", "clean", { fits: ["thing", "place"] }),
  a("marumi", "dirty", { fits: ["thing", "place"] }),
  a("maingay", "noisy", { fits: ["place", "person", "animal"] }),
  a("tahimik", "quiet", { fits: ["place", "person"] }),
  a("madali", "easy", { fits: ["abstract"] }),
  a("mahirap", "difficult", { fits: ["abstract"] }),
  a("mayaman", "rich", { fits: ["person"] }),
  a("matalino", "smart", { fits: ["person", "animal"] }),
  a("tamad", "lazy", { fits: ["person"] }),
  a("masipag", "hardworking", { fits: ["person"] }),
  a("malapit", "near", { fits: ["place"] }),
  a("malayo", "far", { fits: ["place"] }),
  a("maputi", "white", { fits: ["thing", "animal"] }),
  a("maitim", "dark", { fits: ["thing", "animal"] }),
  a("makulay", "colorful", { fits: ["thing", "place"] }),
  a("matigas", "hard", { fits: ["thing", "food"] }),
  a("malambot", "soft", { fits: ["thing", "food"] }),
  a("basa", "wet", { fits: ["thing", "place"] }),
  a("tuyo", "dry", { fits: ["thing", "place"] }),
  a("sira", "broken", { fits: ["thing"] }),
  a("mahangin", "windy", { fits: ["place", "abstract"] }),
  a("maulan", "rainy", { fits: ["abstract"] }),
  a("maaraw", "sunny", { fits: ["abstract"] }),
  a("malakas", "strong", { fits: ["person", "animal", "abstract"] }),
  a("mahina", "weak", { fits: ["person", "animal", "abstract"] }),
  a("matapang", "brave", { fits: ["person", "animal"] }),
  a("maingat", "careful", { fits: ["person"] }),
  a("magulo", "messy", { fits: ["place", "thing"] }),
  a("maayos", "orderly", { fits: ["place", "thing"] }),
  a("sikat", "famous", { fits: ["person", "place"] }),
  a("abala", "busy", { fits: ["person", "place"] }),
  a("libre", "free", { fits: ["thing", "abstract"] }),
  a("makapal", "thick", { fits: ["thing"] }),
  a("manipis", "thin", { fits: ["thing"] }),
  a("malusog", "healthy", { fits: ["person", "food", "animal"] }),
  a("masustansiya", "nutritious", { fits: ["food"] }),
  a("magulang", "grown", { fits: ["food"] }),
  a("hinog", "ripe", { fits: ["food"] }),
];

/** feelings that describe a person and take no ma- prefix rules */
export const STATES = [
  { tl: "gutom", en: "hungry" },
  { tl: "busog", en: "full" },
  { tl: "uhaw", en: "thirsty" },
  { tl: "pagod", en: "tired" },
  { tl: "antok", en: "sleepy" },
  { tl: "galit", en: "angry" },
  { tl: "masaya", en: "happy" },
  { tl: "malungkot", en: "sad" },
  { tl: "takot", en: "scared" },
  { tl: "abala", en: "busy" },
  { tl: "handa", en: "ready" },
  { tl: "excited", en: "excited" },
];

export const COLORS = [
  { tl: "pula", en: "red" },
  { tl: "asul", en: "blue" },
  { tl: "dilaw", en: "yellow" },
  { tl: "berde", en: "green" },
  { tl: "itim", en: "black" },
  { tl: "puti", en: "white" },
  { tl: "kayumanggi", en: "brown" },
  { tl: "kahel", en: "orange" },
  { tl: "lila", en: "purple" },
  { tl: "rosas", en: "pink" },
  { tl: "abo", en: "gray" },
  { tl: "ginto", en: "gold" },
];

// -------------------------------------------------------------------- numbers

export const NUMBERS = [
  { tl: "isa", en: "one", value: 1 },
  { tl: "dalawa", en: "two", value: 2 },
  { tl: "tatlo", en: "three", value: 3 },
  { tl: "apat", en: "four", value: 4 },
  { tl: "lima", en: "five", value: 5 },
  { tl: "anim", en: "six", value: 6 },
  { tl: "pito", en: "seven", value: 7 },
  { tl: "walo", en: "eight", value: 8 },
  { tl: "siyam", en: "nine", value: 9 },
  { tl: "sampu", en: "ten", value: 10 },
  { tl: "labing-isa", en: "eleven", value: 11 },
  { tl: "labindalawa", en: "twelve", value: 12 },
  { tl: "labintatlo", en: "thirteen", value: 13 },
  { tl: "labinlima", en: "fifteen", value: 15 },
  { tl: "dalawampu", en: "twenty", value: 20 },
  { tl: "tatlumpu", en: "thirty", value: 30 },
  { tl: "apatnapu", en: "forty", value: 40 },
  { tl: "limampu", en: "fifty", value: 50 },
  { tl: "isang daan", en: "one hundred", value: 100 },
];

// ---------------------------------------------------------------- time words

/**
 * `aspect` is the verb aspect the phrase forces; `pos` is where it may sit
 * ("final" = after the predicate, "initial" = fronted, which drags the
 * pronoun into a linked form: "Palagi akong ...").
 */
export const TIMES = [
  { tl: "kahapon", en: "yesterday", aspect: "comp", pos: "final" },
  { tl: "kanina", en: "earlier", aspect: "comp", pos: "final" },
  { tl: "kagabi", en: "last night", aspect: "comp", pos: "final" },
  { tl: "noong Lunes", en: "last Monday", aspect: "comp", pos: "final" },
  { tl: "noong isang linggo", en: "last week", aspect: "comp", pos: "final" },
  { tl: "noong isang taon", en: "last year", aspect: "comp", pos: "final" },
  { tl: "kaninang umaga", en: "this morning", aspect: "comp", pos: "final" },
  { tl: "ngayon", en: "now", aspect: "prog", pos: "final" },
  { tl: "sa ngayon", en: "right now", aspect: "prog", pos: "final" },
  { tl: "araw-araw", en: "every day", aspect: "prog", pos: "final", habitual: true },
  { tl: "tuwing Lunes", en: "every Monday", aspect: "prog", pos: "final", habitual: true },
  { tl: "tuwing umaga", en: "every morning", aspect: "prog", pos: "final", habitual: true },
  { tl: "tuwing gabi", en: "every night", aspect: "prog", pos: "final", habitual: true },
  { tl: "palagi", en: "always", aspect: "prog", pos: "initial", habitual: true },
  { tl: "madalas", en: "often", aspect: "prog", pos: "initial", habitual: true },
  { tl: "minsan", en: "sometimes", aspect: "prog", pos: "initial", habitual: true },
  { tl: "bukas", en: "tomorrow", aspect: "cont", pos: "final" },
  { tl: "mamaya", en: "later", aspect: "cont", pos: "final" },
  { tl: "mamayang gabi", en: "tonight", aspect: "cont", pos: "final" },
  { tl: "sa Lunes", en: "on Monday", aspect: "cont", pos: "final" },
  { tl: "sa susunod na linggo", en: "next week", aspect: "cont", pos: "final" },
  { tl: "sa isang taon", en: "in a year", aspect: "cont", pos: "final" },
];

export const DAYS = [
  { tl: "Lunes", en: "Monday" },
  { tl: "Martes", en: "Tuesday" },
  { tl: "Miyerkules", en: "Wednesday" },
  { tl: "Huwebes", en: "Thursday" },
  { tl: "Biyernes", en: "Friday" },
  { tl: "Sabado", en: "Saturday" },
  { tl: "Linggo", en: "Sunday" },
];

/** first names used as dialogue speakers and sentence subjects */
export const NAMES = [
  "Ana", "Ben", "Maria", "Jose", "Lito", "Rosa", "Nena", "Carlo",
  "Divina", "Jun", "Tess", "Rico", "Mila", "Dado", "Luz", "Ramon",
];

// ------------------------------------------------------------------- indexes

export const NOUNS_BY_THEME = NOUNS.reduce((acc, x) => {
  (acc[x.theme] ||= []).push(x);
  return acc;
}, {});

export function nounsFor(theme, cats = null) {
  const pool = NOUNS_BY_THEME[theme] ?? [];
  return cats ? pool.filter((x) => cats.includes(x.cat)) : pool;
}

export function adjectivesFor(cat) {
  return ADJECTIVES.filter((x) => x.fits.includes(cat));
}
